### ISSUE TITLE
Remover o item marcado na imagem.

### ISSUE THREAD

**Issue by mafrawise40** [mafrawise40/informe-front#3]
Remover a barra de pesquisa que não está funcionando.
E o ícone.

![image](https://github.com/mafrawise40/informe-front/assets/116973485/fc87447a-8d81-4492-9048-cc7a27d5da05)

**Comment by martinshellen** [comment]
![image](https://github.com/mafrawise40/informe-front/assets/106033210/033e930b-1eb2-4a3e-b4c9-6936f4d7933a)
